# -*- coding: utf-8 -*-
"""CSCI369 Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-TY5r49BxOyo_dQDe0BBDbhUbA3iC-lO
"""

import time
path = "wordlist.txt"


dict = [
    "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O",
    "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
    "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o",
    "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
    "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
    "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "-", "_", "=", "+",
    "[", "]", "{", "}", ";", ":", "'", '"', "<", ">", ",", ".", "/", "?",
    "\\", "|", "`", "~"
]

def brutemethod(password):
    start = time.time()

    letter = []

    pword = password

    for x in range (0,len(pword)):
        for y in range(0,len(dict)):
            if pword[x] == dict[y]:
                letter.append(dict[y])
                print(letter)
            else:
                print(letter)
        print(letter)
        end = time.time()
        elapsed = end-start
        print(f'Time took {elapsed} seconds to crack.')

def dictmethod(password):
    with open(path, 'r',encoding="utf-8", errors="ignore") as file:
        for x in file:
            guess = x.strip()
            if guess == password:
                print(f"Password found: {guess}")
                return
    print("Password not found in wordlist.")

def hybridmethod(password):

    start = time.time()
    tried = 0

    suffixes = [
        "", "123", "1234", "12345", "2023", "2024", "!", "@", "#", "$",
        "111", "1111", "007", "99", "00", "2020", "999", "321", "666", "abc"
    ]
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        for raw in f:
            word = raw.strip()
            variants = [
                word,
                word.capitalize(),
                word[::-1],
            ]

            for v in variants:
                for suf in suffixes:
                    guess = v + suf
                    tried += 1
                    if guess == password:
                        elapsed = time.time() - start
                        print(f"Password found: {guess}")
                        print(f"Guesses tried : {tried}")
                        print(f"Time taken     : {elapsed:.4f}s")
                        return

    print(f"Password not found.")
brutemethod("Timothy")
dictmethod("123456789")
hybridmethod("Password123$")